"""empty message

Revision ID: 2d7ac078110c
Revises: 
Create Date: 2018-09-27 20:26:09.119821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7ac078110c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('des_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('des_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('des_id'),
    sa.UniqueConstraint('des_name')
    )
    op.create_table('photo',
    sa.Column('p_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('des_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['des_id'], ['destination.des_id'], ),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('destination')
    # ### end Alembic commands ###
